e main.h
vsplit main.cpp
tabnew Univers.h
vsplit Univers.cpp
tabnew Astre.h
vsplit Astre.cpp
tabnew RenduGraphique.h
vsplit RenduGraphique.cpp
tabnew Interface/BoiteHauteInterface.h
vsplit Interface/BoiteHauteInterface.cpp
tabnew Interface/BoiteInfoAstre.h
vsplit Interface/BoiteInfoAstre.cpp
