######################################################################
# Automatically generated by qmake (2.01a) dim. juin 3 18:14:23 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fenetre.h main.h
SOURCES += fenetre.cpp main.cpp
