.Sh NAME
.Nm Gravastre 2.0
.Sh SYNOPSIS
.Nm Gravastre
.Op Fl t
.Sh DESCRIPTION
.Ss Touches disponibles : // incomplet
.Bl -item
.It
Pave Numerique et Chiffres clavier, pour pouvoir donner des nombres (affiches en haut). Utilisez la touche E pour les puissances et le tiret '-' pour le signe
.It
Pause, pour mettre en pause
.It
M, pour arreter/faire jouer la musique
.It
A, pour lancer la modification de l'astre selectionne
.It
Fleches, pour se deplacer
.It
Espace, pour prendre comme referentiel l'astre selectionne
.It
Escape, pour quitter
.El
.Ss Utilisation de la sourie : // incomplet
.Bl -item
.It
Clic droit, utilise en clique-glisse permet de bouger le cadre
.It
Clic gauche, sur un astre, permet de le selectionner. Sinon, l'astre est deselectionne
.It
Clic gauche, utilise en clique-glisse sur le cadre d'information de l'astre selectionne permet de bouger ce dernier
.It
Molette, pour le zoom
.El
.Sh Modifier un astre : // incomplet
Chose possible en selectionnant l'astre voulut et en appuyant sur A.
La simulation est mise en pause, et le tampon est vide.
Remplissez ce dernier (avec le pave numerique), puis choisissez quel parametre utiliser.
.Sh EXAMPLES
Taper successivement 1e13M modifie la masse de l'astre en 1*10^13 unite de poids
.Sh SEE ALSO
None
.Sh OTHER
.Ss Indications sur les unites utilisees : 
Les unitees utilisees ne correspondent pas a une valeur reelle.
Cependant, un ordre de grandeur est comprehensible, et calculable.
300 px equivaux environ a 1 unite astronomique. (1e11 metres)
Multipliez les poids par 1e17 pour avoir des poids realistes
.Sh AUTHORS
.Bl -item
.It
Code : Lucas B.
.It
Doc : Lucas B. & matael
.El
